include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = WaveAway

WaveAway_FILES = sangRootListController.m
WaveAway_FRAMEWORKS = UIKit
WaveAway_PRIVATE_FRAMEWORKS = Preferences
WaveAway_EXTRA_FRAMEWORKS += Cephei CepheiPrefs
WaveAway_INSTALL_PATH = /Library/PreferenceBundles
WaveAway_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
